---
title: "Usage examples"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Example 1. Interactive time series

```{r example_1}
library(ineapir)
#library(ggplot2)
library(plotly)

# Filter cpi overall index
filter <- list(values = c("variación anual" , "índice general"))

# Request data of cpi
# Table url: https://www.ine.es/jaxiT3/Tabla.htm?t=50902&L=0
general <- get_data_table(idTable = 50902, filter = filter, unnest = TRUE,
                          tip = "A" )

# Filter core cpi
filter <- list(values = c("variación anual" , 
                       "general sin alimentos no elaborados ni productos energéticos"))

# Request data of core cpi
# Table url: https://www.ine.es/jaxiT3/Tabla.htm?t=50907&L=0
subyacente <- get_data_table(idTable = 50907, filter = filter, unnest = TRUE,
                             tip = "A" )

# Format Fecha column as date
general$Fecha <- as.Date(general$Fecha)
subyacente$Fecha <- as.Date(subyacente$Fecha)

# Plot cpi overall index
fig <- plot_ly(general, x = ~Fecha, y = ~Valor, name = 'General',
               type = 'scatter', mode = 'lines')

## Plot core cpi
fig <- fig %>% add_trace(y = ~subyacente$Valor, name = 'Subyacente',
                         mode = 'lines') %>%
  layout(yaxis = list(title="Variación anual (%)"),
         legend = list(title=list(text='<b> IPC </b>'),
                       x = 0.25,
                       y = -0.25,
                       orientation = 'h'),
         hovermode = 'x') %>%
  config(displayModeBar = FALSE)

fig

```

## Example 2. Population pyramid

```{r example_2}
#library(dplyr, quietly = TRUE)
library(forcats)

# Filter for total population of men and women 
filter <- list(nacionalidad = "total", sexo = c("hombres", "mujeres"))

# Table: Resident population by date, sex, age group and nationality
# Table url: https://www.ine.es/jaxiT3/Tabla.htm?t=56936&L=0
poblacion <- get_data_table(idTable = 56936, filter = filter, validate = FALSE, 
                            tip = "AM", unnest = TRUE, extractmetadata = TRUE)

# Filter and calculate percentages
pob <- poblacion %>% 
  filter(Grupo.quinquenal.de.edad != "Todas las edades" & T3_Periodo == "1 de enero de") %>%
  group_by(Anyo) %>% 
  mutate(Total = sum(Valor), 
         Porcentaje = Valor/Total*100, 
         Grupo.quinquenal.de.edad = fct_inorder(trimws(Grupo.quinquenal.de.edad))) %>% ungroup() %>%
  mutate(Porcentaje = ifelse(Sexo == "Hombres",
                             -Porcentaje, Porcentaje))
  
# Pyramid using plotly
fig <- plot_ly(pob, x = ~Porcentaje , y = ~Grupo.quinquenal.de.edad, color = ~Sexo, 
               colors = c("blue", "red"), type = 'bar', frame = ~Anyo) %>% 
       layout(bargap = 0.1, barmode = 'overlay',
              xaxis = list(hoverformat = '.2f'),
              yaxis = list(title="Edad"),
              title = 'Población residente por sexo y grupo de edad') %>%
       animation_slider(currentvalue = list(prefix = "Año: ")) %>%
       config(displayModeBar = FALSE)

fig

```


## Example 3. Interactive bar chart.
```{r example_3}

# Filter for unemployment rates
filter = list(ccaa = "", sexo = "ambos", edad = "total")

# Table: Unemployment rates by different age groups, sex and Autonomous Community
# Table url: https://www.ine.es/jaxiT3/Tabla.htm?t=4247&L=0
paro <- get_data_table(idTable = 4247, filter = filter, nlast = 1, inecode = TRUE,
                       unnest = TRUE, extractmetadata = TRUE, tip = "AM")

# Bar chart using plotly
fig <- plot_ly(paro, 
               x = ~paro$Comunidades.y.Ciudades.Autónomas,
               y = ~Valor, type = "bar") %>%
       config(displayModeBar = FALSE) %>%
       layout(xaxis = list(title="", tickangle = -45),
              yaxis = list(title = "Tasa de paro (%)"),
              title = sprintf("Tasa de paro por Comunidad Autónoma (%s %s)",
                              paro$Anyo[1], paro$T3_Periodo[1])
              )

fig
  
```

## Example 4. Interactive map.
```{r example_4}
library(leaflet)
library(sf)

# Get the boundaries of the autonomous communities
ccaa <- read_sf("https://difusion.interna.ine.es/wstempus/geojs/ES/CONTORNOS/70")

# Select a set on columns from data of example 3
paro <- subset(paro, select = c("Comunidades.y.Ciudades.Autónomas.Id", "T3_Periodo", "Anyo","Valor"))

# Join boundaries information with data information
ccaa <- merge(ccaa, paro, by.x = "id_region", by.y = "Comunidades.y.Ciudades.Autónomas.Id" )

# Palette of the legend
pal <- colorBin("plasma", domain = NULL, bins = c(quantile(ccaa$Valor)))

# Labels of the map
labels <- sprintf(
  "<strong>%s</strong><br/> Tasa de paro: %s%% ",
  ccaa$nom_region, ccaa$Valor
) %>% lapply(htmltools::HTML)

# Create the map
m <- leaflet(ccaa) %>% 
  addTiles() %>%
  #addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  setView(-4, 40, zoom = 6) %>%
  addPolygons(fillOpacity = 0.8,
              fillColor = ~pal(Valor),
              weight = 1,
              color = "white",
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"
              ),
              highlightOptions = highlightOptions(fillOpacity = 1, bringToFront = TRUE, 
                                                  weight = 2, color = "white")
  ) %>%
  addLegend(pal = pal, values = ~Valor, opacity = 1.0, position = "bottomright",
            labFormat = labelFormat(suffix = "%", digits = 2),
            title = sprintf("Tasa de paro (%s %s)",
                            paro$T3_Periodo[1], paro$Anyo[1]))



m
```

